### ISSUE TITLE
Author, I would like to ask the following questions, thank you very much, only for academic purposes,thanks.

### ISSUE THREAD

**Issue by adwxy** [MCG-NKU/SOD100K#11]
FileNotFoundError: [Errno 2] No such file or directory: "CSNet/results/csnet-L-x2/FmeasureResults_csnet-L-x2_['DUTS-TE', 'ECSSD'].txt"

**Comment by gasvn** [comment]
Maybe you need to run python xxx.py in the CSNet folder.  Let me know if you still cannot solve the problem.

**Comment by user-wu** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: "CSNet/results/csnet-L-x2/FmeasureResults_csnet-L-x2_['DUTS-TE', 'ECSSD'].txt"

I have the same question. Have you solved the problem yet, could you please tell you how to deal? thank you, and best wish.

**Comment by gasvn** [comment]
> > FileNotFoundError: [Errno 2] No such file or directory: "CSNet/results/csnet-L-x2/FmeasureResults_csnet-L-x2_['DUTS-TE', 'ECSSD'].txt"
> 
> I have the same question. Have you solved the problem yet, could you please tell you how to deal? thank you, and best wish.

You need to run python xxx.py in the CSNet folder
