### ISSUE TITLE
[bug-report] test.py failed when loading gray-scale image in ECSSD dataset

### ISSUE THREAD

**Issue by mrbulb** [MCG-NKU/SOD100K#13]
`0557.jpg` is a gray-scale image in ECSSD dataset. when runing CSNet‘s [testing code](https://github.com/MCG-NKU/SOD100K/blob/master/CSNet/test.py)
```
python test.py --config configs/csnet-L-x2.yml
```
error will occur

> Traceback (most recent call last):
  File "test.py", line 135, in <module>
    main()
  File "test.py", line 53, in main
    test(model, cfg.TEST.DATASETS, loadepoch)
  File "test.py", line 91, in test
    img = np.transpose((img - mean) / std, (2, 0, 1))
ValueError: operands could not be broadcast together with shapes (224,224) (3,)

May be you can judge the gray-scale image & convert it into RGB image
```python
img = skimage.img_as_float(
    io.imread(os.path.join(img_dir, img_name)))
if len(img.shape) == 2:
    img = skimage.color.gray2rgb(img)
```

**Comment by gasvn** [comment]
Thanks for your bug report, we will fix this bug.
