### ISSUE TITLE
saliency maps

### ISSUE THREAD

**Issue by zhaozhirui** [MCG-NKU/SOD100K#14]
You only provide the saliency maps of CSF+Res2Net. Can you provide the saliency maps of CSNet?

**Comment by gasvn** [comment]
Here is the saliency map for CSNet.
https://mailnankaieducn-my.sharepoint.com/:u:/g/personal/shgao_mail_nankai_edu_cn/EWcW3TrbtUZIrKHLjuT2Pv4BBQYK4ZkKHYhC3NvP6R-WgA?e=urfoVB
