### ISSUE TITLE
export CSNet to ONNX

### ISSUE THREAD

**Issue by PanYuX** [MCG-NKU/SOD100K#17]
how can i export CSNet to onnx?

**Comment by xiongzhu666** [comment]
> how can i export CSNet to onnx?

When I export onnx, I faced the problem as below, how did you solve it?? thanks
![image](https://user-images.githubusercontent.com/52955431/160736519-51399eca-8533-47c8-a389-fee5a011a03e.png)

**Comment by rakesh-reddy95** [comment]
How is this solved and converted to onnx?
