### ISSUE TITLE
Unresolved reference 'redefine_model' 

### ISSUE THREAD

**Issue by Pratyeka** [MCG-NKU/SOD100K#20]
Hi! First of all, thanks for sharing your great work on salient object detection!

When i reading the source code 【SOD100K/CSNet_training/model/csnet.py/build_model]】
I cannot find the implementation of the function 'redefine_model' in  line918.

please give me some help!

**Comment by gasvn** [comment]
Thanks for your reminder. The function redefine_model is similar to  function finetune_model. This function is no longer used in our final version. Thanks. We have removed this function in our new version.
