### ISSUE TITLE
can not link to the pre-trained model in onedrive

### ISSUE THREAD

**Issue by junedgar** [MCG-NKU/SOD100K#3]
Thank you for your great work!
I tried to do some test, but find there was not right link for the pre-trained model.
Can you fix this problem?

**Comment by gasvn** [comment]
Thanks for mentioning, I will upload the pre-trained model later today.

**Comment by gasvn** [comment]
The link to pre-trained model: https://mailnankaieducn-my.sharepoint.com/:u:/g/personal/shgao_mail_nankai_edu_cn/EWYBOMYWNklLlVG38QlmozkBEIPgaCzsrrPq7BBFUEGjRg?e=ZTtbnM
