### ISSUE TITLE
PallMSBlock里分多个msconv的意义何在？

### ISSUE THREAD

**Issue by mozpp** [MCG-NKU/SOD100K#5]
你把一个256 * 256 * 3 * 3的卷积分成5个51 * 256 * 3 * 3的卷积、再concat。意义何在？
理论上没区别啊

**Comment by gasvn** [comment]
After the  cross-stage gOctConv, each scale in the feature set is processed by the  msconv.

**Comment by mozpp** [comment]
> After the cross-stage gOctConv, each scale in the feature set is processed by the msconv.

Of course I know each scale in the feature set is processed by the msconv.
But my question is: inside one MSBlock, you use 5 convs. I think there is no difference between one 256 * 256 conv and five 51 * 256 conv.
![image](https://user-images.githubusercontent.com/25809906/87923986-da13b180-cab0-11ea-9d91-9272fa867e3d.png)

**Comment by gasvn** [comment]
They have different dilations.

**Comment by mozpp** [comment]
哦哦
