### ISSUE TITLE
saliency maps

### ISSUE THREAD

**Issue by hongminglin08** [MCG-NKU/SOD100K#6]
Can you provide the saliency maps of yours?

**Comment by ishgao** [comment]
I will upload it today.

**Comment by gasvn** [comment]
I will upload it today.

**Comment by gasvn** [comment]
The link to download saliency map: https://mailnankaieducn-my.sharepoint.com/:u:/g/personal/shgao_mail_nankai_edu_cn/EVBf1QE8Y5ZBhma4MEYABNMBnnMxOMiS6qAyPz3Kkv6bqA?e=jpcIjP

**Comment by hongminglin08** [comment]
Thank you very much!
