### ISSUE TITLE
关于backbone

### ISSUE THREAD

**Issue by chiukin** [MCG-NKU/SOD100K#7]
请问有没有 ResNet50 的版本以及相应得到的saliency maps，而不是 Res2Net50

**Comment by gasvn** [comment]
Our main contribution is the light weight model CSNet. The CSF + Res2Net is only used to prove the effectiveness of a part of components in CSNet. Similar to the ILblock in CSNet, Res2Net also enhances the in-layer multi-scale ability of the network. We recommend to use Res2Net to get better performance on large SOD models with no extra cost.
