### ISSUE TITLE
csf-res2net里网络结构注释了fc层但是onedrive里的pth参数没有删掉fc层参数

### ISSUE THREAD

**Issue by splinter21** [MCG-NKU/SOD100K#8]
导致net.load_state_dict()报错

RuntimeError: Error(s) in loading state_dict for CSFNet:
	Unexpected key(s) in state_dict: "base.fc.weight", "base.fc.bias".

**Comment by gasvn** [comment]
Thanks for the bug report. I have changed strict =False when load model. It should solve this problem. Please let me know if you still have this problem.

**Comment by splinter21** [comment]
When loading the weights, deleting these two keys and it's ok to use "strict=True".
